### ISSUE TITLE
My PR in hacktober was excluded

### ISSUE THREAD

**Issue by UlissesJunior** [typhonshambo/hacktoberfest-2022#27]
![image](https://user-images.githubusercontent.com/80963163/194056972-6701da1e-ac67-4c18-91ea-249d4bb4c007.png)

**Comment by typhonshambo** [comment]
Same issue happened to everyone!
i don't know why they excluded this repository :(

**Comment by shubhambaghel34** [comment]
@typhonshambo @UlissesJunior Yes Mine too, even we have correct hacktober labels in repo

**Comment by typhonshambo** [comment]
It's probably because someone reported this repo as spammy and against the values of hacktobefest

**Comment by shubhambaghel34** [comment]
> It's probably because someone reported this repo as spammy and against the values of hacktobefest

owner should get a notification for this at least so they can analyze
